sudo: false
dist: xenial
language: python
matrix:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    # hack py37, py38 to use a different Travis worker type
    # sudo:required gets us the VM builds where these pythons work
    - python: "3.7"
      sudo: required
    - python: "3.8-dev"
      sudo: required
    - python: "pypy"
    - python: "pypy3"
    - python: "nightly"
    - os: windows
      language: sh
      python: "2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
  allow_failures:
    - python: "3.8-dev"
    - python: "pypy"
    - python: "pypy3"
    - python: "nightly"
cache: pip
install:
  - pip install -e '.[development]'
script:
  - tox -e py  # invoke with calling python
