sudo: false
dist: xenial
language: python
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.8"
      env: TOXENV=lint
    - name: "py2.7 + windows"
      os: windows
      language: shell
      python: "2.7"
      env: TOXENV=py27 PATH="/c/Python27:/c/Python27/Scripts:$PATH"
      before_install:
        - choco install python2
        - python -m pip install --upgrade pip wheel
    - name: "py3.8 + windows"
      os: windows
      language: shell
      python: "3.8"
      env: TOXENV=py38 PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python3
        - python -m pip install --upgrade pip wheel
cache: pip
install:
  - pip install tox
script:
  - tox
